### ISSUE TITLE
Create unit and integration tests

### ISSUE THREAD

**Issue by amacneil** [foxglove/electron-socket#5]
This library has no test coverage right now and is susceptible to regressions that only show up when you try to use the `ROS 1 Native` connector in Foxglove Studio.

Since this library is intrinsically tied to Electron implementation details, for full coverage we need an integration test that compiles a small electron app, runs it, and confirms socket and server creation and communication works as expected.

**Comment by defunctzombie** [comment]
I recommend using https://github.com/microsoft/playwright and looking at what studio does for its integration test.

**Comment by defunctzombie** [comment]
https://github.com/foxglove/electron-socket/pull/7 foundation to build on

**Comment by jaguardo** [comment]
Is there a way to easily by-pass the requirement for playwright? i.e. not require integration tests?
During `yarn install`, I got the following error:
```
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 4s 488ms
➤ YN0000: ┌ Link step
➤ YN0007: │ playwright@npm:1.32.2 must be built because it never has been before or the last one failed
➤ YN0009: │ playwright@npm:1.32.2 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-cbb3e93b/build.log)
➤ YN0000: └ Completed in 7s 474ms
➤ YN0000: Failed with errors in 17s 139ms
```

and the log file
```
Error: ERROR: Playwright does not support firefox on ubuntu18.04-arm64
    at Registry._downloadExecutable (/data/source/studio/node_modules/playwright-core/lib/server/registry/index.js:641:37)
    at Object._install (/data/source/studio/node_modules/playwright-core/lib/server/registry/index.js:434:28)
    at Registry.install (/data/source/studio/node_modules/playwright-core/lib/server/registry/index.js:614:26)
    at async installBrowsersForNpmInstall (/data/source/studio/node_modules/playwright-core/lib/server/registry/index.js:790:3)
```
Im trying to get things running on an nvidia box that isn't the easiest to upgrade ubuntu versions (which i am considering as a correction to this).

**Comment by defunctzombie** [comment]
There is no easy way to bypass the requirement for playwright - however playwright is not in the current packages dependencies.

**Comment by jaguardo** [comment]
> There is no easy way to bypass the requirement for playwright - however playwright is not in the current packages dependencies.

Copy... must be a foxglove/studio requirement only then? Thanks!
